---
debname: facter
debver: 3.14.12-1
dl_path:
  name: facter-3.14.12-1.tar.gz
  url: https://salsa.debian.org/puppet-team/facter/-/archive/debian/3.14.12-1/facter-debian-3.14.12-1.tar.gz
  md5sum: 2394099bd9d6c63eaa1fb5fda5e79fca
  sha256sum: 7e3160b584bfaa2863643ee23aa84abdec9dcea292701623cf750d23df0e53f8
revision:
  dist: $STX_DIST
  PKG_GITREVCOUNT: true
