---
debname: puppet-lvm
debver: 1.4.0-1
dl_path:
    name: puppet-lvm-1.4.0.tar.gz
    url: https://github.com/puppetlabs/puppetlabs-lvm/archive/refs/tags/v1.4.0.tar.gz
    md5sum: c0309a7dfd408f16586310f9398408f0
revision:
    dist: $STX_DIST
    PKG_GITREVCOUNT: true
