---
debname: puppet-drbd
debver: 0.5.2-0
dl_path:
  name: puppet-drbd-0.5.2-0.tar.gz
  url: https://github.com/voxpupuli/puppet-drbd/archive/refs/tags/v0.5.2.tar.gz
  md5sum: 2e828b92bac292461cd90d298fa4102f
  sha256sum: 9d342c31db680503d87f3307565a2984af1b3a8f797ed4a8b778e9dd898565f1
revision:
  dist: $STX_DIST
  PKG_GITREVCOUNT: true
