---
debname: puppet-boolean
debver: 2.0.2-0
dl_path:
  name: puppet-boolean-2.0.2-0.tar.gz
  url: https://codeload.github.com/voxpupuli/puppet-boolean/tar.gz/refs/tags/v2.0.2
  md5sum: c724f206a25561cadb024d6791b73eea
  sha256sum: d595e4e50d7c68d8ef1366465a3e019075d5ff3b9b5a972f8340b0bb13d05934
revision:
  dist: $STX_DIST
  PKG_GITREVCOUNT: true
