---
debname: puppet-module-puppetlabs-firewall
debver: 1.12.0-1
dl_path:
  name: puppet-module-puppetlabs-firewall-1.12.0-1.tar.gz
  url: https://salsa.debian.org/puppet-team/puppet-module-puppetlabs-firewall/-/archive/debian/1.12.0-1/puppet-module-puppetlabs-firewall-debian-1.12.0-1.tar.gz
  md5sum: d54a6e017792ca19f6227cc61222c89b
  sha256sum: 850d80d0dae673bf5c79e0968437ac37764f3d419502c37a8dcc4ace0f5ebd0a
revision:
  dist: $STX_DIST
  PKG_GITREVCOUNT: true
