---
debname: puppet-module-puppetlabs-postgresql
debver: 6.7.0-2
dl_path:
  name: puppet-module-puppetlabs-postgresql-6.7.0-2.tar.gz
  url: https://salsa.debian.org/puppet-team/puppet-module-puppetlabs-postgresql/-/archive/debian/6.7.0-2/puppet-module-puppetlabs-postgresql-debian-6.7.0-2.tar.gz
  md5sum: 4ea08eb9aeb3d80b4ef0d41f4219557e
  sha256sum: 035cd27d6754112da9b3f55364d75cb5aa7dc014deb61dd5e40e67f4e1f48fa5
revision:
  dist: $STX_DIST
  PKG_GITREVCOUNT: true
